#include "Save/VTGSaveable.h"

// The interface's GetSaveId / ShouldSaveTransform are BlueprintNativeEvents whose default
// implementations are generated by UHT (returning NAME_None / false). The SaveCoordinator does
// the actual serialisation generically, so there is nothing to implement here.
